routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController as Home;
use App\Http\Controllers\Catalog\CategoryController as Category;
use App\Http\Controllers\Catalog\BookController as Book;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return redirect('home');});
Route::get('/home', [Home::class, 'index'])->name('home');
Route::resource('/categories', Category::class);
Route::resource('/books', Book::class);

// Auth::routes();

app/Models/Catalog/Book.php
<?php

namespace App\Models\Catalog;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;
    protected $fillable = [
        'status',
        'author',
        'tittle',
        'tittle_page'
    ];

    public function categories()
    {
      return $this->belongsToMany(Category::class);
    }
    public function category()
    {
     return $this->hasOne(Category::class , 'id' , 'category_id');
    }

    // * Scopes
    public function scopeCategory($query, $category_id,$table = "")
    {
        if (!is_null($category_id) && $category_id !== "%" && $category_id !== "")
        {
          return !empty($table) ? $query->where("{$table}.category_id", $category_id): $query->where('category_id', $category_id);

        }

    }
    public function scopeStatus($query, $status,$table = "")
    {
        if (!is_null($status) && $status !== "%" && $status !== "")
        {
          return !empty($table) ? $query->where("{$table}.status", $status): $query->where('status', $status);

        }

    }
  
}

app/Http/Controllers/Catalog/BookController.php
<?php

namespace App\Http\Controllers\Catalog;

use App\Http\Controllers\Controller;


use App\Models\Catalog\Book;
use App\Repositories\Catalog\BookRepository;
use App\Repositories\Catalog\CategoryRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BookController extends Controller
{

    public $book_repository;
    public $category_repository;

    public function __construct()
    {
        $this->book_repository = new BookRepository;
        $this->category_repository = new CategoryRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = $this->category_repository->index(1);
        $books = $this->book_repository->index($request->status_books, $request->status_catagory);

        return view('catalogues.book.index', [
            'books' => $books,
            'categories' => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $obj = new Book();
        $categories = $this->category_repository->index(1);
        return view('catalogues.book.create', [
            'obj' => $obj,
            'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'tittle' => ['required', 'string', 'max:150'],
            'author' => ['required', 'string', 'max:150'],
            'tittle_page' => ['required', 'image']
        ]);

        DB::beginTransaction();
        try {
            $response = $this->book_repository->store($request);
            if (!$response->success) {
                DB::rollBack();
                return back()->withInput()->with(
                    'error',
                    __('msg.html_error_save') . $response->code .
                        __('msg.error_message') . $response->message
                );
            }
            DB::commit();
            return redirect()->route('books.index')->with('success', $response->message);
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->withInput()->with(
                'error',
                __('msg.html_error_save') . $th->getCode() .
                    __('msg.error_message') . $th->getMessage()
            );
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Catalog\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $obj = $this->book_repository->find($id);
        $categories = $this->category_repository->index(1);
        return view('catalogues.book.edit', [
            'obj' => $obj,
            'categories' => $categories
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Catalog\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        DB::beginTransaction();
        $obj = Book::find($id);

        try {

            $response = $this->book_repository->update($request, $obj);
            // dd($response);
            if (!$response->success) {
                DB::rollBack();
                return back()->withInput()->with(
                    'error',
                    __('msg.html_error_save') . $response->code .
                        __('msg.error_message') . $response->message
                );
            }
            DB::commit();

            return redirect()->route('books.index')->with('success', $response->message);
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->withInput()->with(
                'error',
                __('msg.html_error_save') . $th->getCode() .
                    __('msg.error_message') . $th->getMessage()
            );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Catalog\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        //
    }
}

resources/views/catalogues/book/create.blade.php
@extends('layouts.app')

@push('css_after')
<link rel="stylesheet" href="{{ asset('/js/plugins/flatpickr/themes/material_green.css') }}">
<link rel="stylesheet" href="{{ asset('/js/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('/js/plugins/select2/css/select2-bootstrap4.min.css') }}">
@endpush

@section('page-title')
{{ __('Registrar Libro') }}
@endsection

@section('block-header')
@if(session()->has('error'))
<div class="alert alert-danger alert-dismissible" role="alert">
    <p class="mb-0">
        {{session('error')}}
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif
@endsection

@section('block-content')
<form id="crud_form" method="POST" action="{{ route('books.store')}} " enctype="multipart/form-data">
    @include('catalogues.book.form')
</form>
@endsection

@push('js_after')
<script src="{{ asset('/js/plugins/select2/js/select2.full.min.js') }}"></script>
<script src="{{ asset('/js/plugins/select2/js/i18n/es.js') }}"></script>
<!-- Page JS Helpers (Flatpickr + BS Datepicker + BS Maxlength + Select2 + Masked Inputs + Ion Range Slider + BS Colorpicker plugins) -->
{{-- <script>One.helpersOnLoad(['jq-select2']);</script> --}}
<script>
    const mSelect = $(".select2-multiple");

    mSelect.select2({
        language: "es"
        , theme: 'bootstrap4'
    , });

</script>
<script>
    One.helpersOnLoad(['jq-select2']);

</script>

@endpush

resources/views/catalogues/book/edit.blade.php
@extends('layouts.app')

@push('css_after')
    <link rel="stylesheet" href="{{ asset('/js/plugins/flatpickr/themes/material_green.css') }}">
    <link rel="stylesheet" href="{{ asset('/js/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/js/plugins/select2/css/select2-bootstrap4.min.css') }}">
@endpush

@section('page-title')
    {{ __('Editar Libro') }}
@endsection

@section('block-header')
@if(session()->has('error'))
<div class="alert alert-danger alert-dismissible" role="alert">
    <p class="mb-0">
        {{session('error')}}
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif
@endsection

@section('block-content')
<form id="crud_form" method="POST" action="{{ route('books.update', $obj) }}" class="crud_form">
    @method('PATCH')
    @include('catalogues.book.form' )
</form>
@endsection

@push('js_after')
<script src="{{ asset('/js/plugins/select2/js/select2.full.min.js') }}"></script>
<script src="{{ asset('/js/plugins/select2/js/i18n/es.js') }}"></script>
<!-- Page JS Helpers (Flatpickr + BS Datepicker + BS Maxlength + Select2 + Masked Inputs + Ion Range Slider + BS Colorpicker plugins) -->
{{-- <script>One.helpersOnLoad(['jq-select2']);</script> --}}
<script>
    const mSelect = $(".select2-multiple");

    mSelect.select2({
        language: "es"
        , theme: 'bootstrap4'
    , });

</script>
<script>One.helpersOnLoad(['jq-select2']);</script>

@endpush

resources/views/catalogues/book/form.blade.php
@csrf
<div class="form-group row mb-4">
    @if (!is_null($obj->id))
    <div class="form-group col-lg-3 col-md-4 col-sm-12">
        <label for="status">{{ __('Estado') }} <span class="text-danger">*</span></label><br>
        <select id="status" name="status" class="form-select @error('status') is-invalid @enderror" required>
            <option value="" {{ (old( "status",$obj->status) === null ) ? 'selected' :'' }}>{{ __('Seleccione') }}</option>
            <option value="1" {{ (old( "status",$obj->status) == "1" )  ? 'selected' :'' }}> {{ __('Activo') }}</option>
            <option value="0" {{ (old( "status",$obj->status) == "0" )  ? 'selected' :'' }}> {{ __('Inactivo') }}</option>
        </select>
        <span class="invalid-feedback" role="alert">
            <strong>@error('status'){{ $message }}@enderror</strong>
        </span>
    </div>
    @endif


    <div class="form-group  mb-4 col-lg-3 col-md-4 col-sm-12">
        <label for="category_id">{{ __('Categorias') }}<span class="text-danger">*</span></label><br>
        <select class="form-control js-select2 form-select select2-multiple" id="catagories" name="categories[]" data-placeholder="Seleccione.." multiple="multiple" required>
            <option value="">{{__('Seleccione..')}}</option>
            @foreach ($categories as $category)
            <option {{ collect(old('categories',$obj->categories->pluck('id')))->contains($category->id) ? 'selected' :'' }} value="{{$category->id}}">{{$category->name}}</option>
            @endforeach

        </select>


    </div>

    <div class="form-group col-lg-3 col-md-4 col-sm-12">
        <label for="tittle">{{ __('Titúlo') }} <span class="text-danger">*</span></label><br>
        <input id="tittle" name="tittle" type="text" class="maxlength form-control @error('tittle') form-control-alt is-invalid @enderror" placeholder="{{ __('Nombre') }}" value="{{ old('tittle', $obj->tittle) }}" maxlength="50" required>
        <span class="invalid-feedback" role="alert">
            <strong>@error('tittle') {{ $message }} @enderror</strong>
        </span>
    </div>
    <div class="form-group col-lg-3 col-md-4 col-sm-12">
        <label for="author">{{ __('Author') }} <span class="text-danger">*</span></label><br>
        <input id="author" name="author" type="text" class="maxlength form-control @error('author') form-control-alt is-invalid @enderror" placeholder="{{ __('Nombre') }}" value="{{ old('author', $obj->author) }}" maxlength="50" required>
        <span class="invalid-feedback" role="alert">
            <strong>@error('author') {{ $message }} @enderror</strong>
        </span>
    </div>
    <div class="form-group col-lg-3 col-md-4 col-sm-12">
        <label for="tittle_page">{{ __('Portada') }} <span class="text-danger">*</span></label><br>
        <div class="custom-file">
            <input id="tittle_page" name="tittle_page" type="file" class="custom-file-input form-control @error('tittle_page') form-control-alt is-invalid @enderror" data-toggle="custom-file-input">
        </div>

        <span class="invalid-feedback" role="alert">
            <strong>@error('tittle_page'){{ $message }}@enderror</strong>
        </span>
    </div>
    <div class="col-md-6 col-lg-4 col-xl-3 animated fadeIn">
        <label for="tittle_page">{{ __('Portada') }}</label><br>
        <a target="_blank" class="img-link img-link-zoom-in img-thumb img-lightbox magnific-pic" href="{{ (is_null($obj->tittle_page)) ? '/media/avatars/avatar0.jpg' : Storage::disk('book_tittle_page')->url($obj->tittle_page) }}">
            <img class="img-fluid" style="width: 6rem;" src="{{ (is_null($obj->tittle_page)) ? '/media/avatars/avatar0.jpg' : Storage::disk('book_tittle_page')->url($obj->tittle_page) }}" alt="Logo">
        </a>
    </div>

</div>
<div class="form-group row mb-4">
    <div class="col-md-12">
        <button id="send" type="submit" class="btn btn-primary btn-md float-right">
            <i class="{{ (is_null($obj->id))  ? 'fas fa-save' : 'fas fa-sync-alt' }} mr-1"></i>
            {{ (is_null($obj->id)) ? __('Guardar') : __('Actualizar') }}
        </button>
        <a href="{{ route('categories.index') }}" class="btn btn-light btn-undo btn-md mr-2 float-right">
            <i class="fas fa-undo-alt mr-1"></i>{{ __('Regresar') }}
        </a>
    </div>
</div>

resources/views/catalogues/book/index.blade.php
@extends('layouts.app')

@push('css_before')
<link rel="stylesheet" href="{{ asset('js/plugins/datatables-bs5/css/dataTables.bootstrap5.min.css') }}">
<link rel="stylesheet" href="{{ asset('js/plugins/datatables-buttons-bs5/css/buttons.bootstrap5.min.css') }}">
<link rel="stylesheet" href="{{ asset('/js/plugins/magnific-popup/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('/js/plugins/datatables-responsive-bs5/css/responsive.bootstrap5.min.css') }}">
@endpush

@section('page-title')
{{ __('Lista de Libros') }}
@endsection

@section('buttons')
<a type="button" href="{{route('books.create')}}" class="btn btn-success">Registrar Libro</a>
@endsection

@section('block-extra')

@if(session()->has('success'))
<div class="alert alert-success alert-dismissible" role="alert">
    <p class="mb-0">
        {{session('success')}}
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif




<div class="block block-rounded">
    <div class="block-content block-content-full">
            @csrf
            @php
            $status = request('status_books');
            $category = request('status_catagory');
            @endphp
            <form method="GET" action="" role="search" class="form-search">
                <div class="block-header block-header-default text-center">
                    <div class="form-group mb-4  form-group-status col-md-3 col-sm-12" id="form-group-status">
                        <label for="status">{{ __('Estado') }}</label>
                        <select name="status_books" class="form-select" id="filter-index-status-books">
                            <option value='%' {{ ( $status == '%' ) ? 'selected' : '' }}>{{ __('Todos') }}</option>
                            <option value='1' {{ ( $status == '1' ) ? 'selected' : '' }}>{{ __('Activos') }}</option>
                            <option value='0' {{ ( $status == '0' ) ? 'selected' : '' }}>{{ __('Inactivos') }}</option>
                        </select>
                    </div>
                    <div class="form-group mb-4 col-md-3 col-sm-12" id="form-group-status">
                        <label for="status">{{ __('Categorias') }}</label>
                        <select name="status_catagory" class="form-select" id="filter-index-status-books">
                            <option value='%' {{ ( $category == '%' ) ? 'selected' : '' }}>{{ __('Todos') }}</option>
                            @foreach ($categories as $item)
                            <option value="{{$item->id}}" {{ ( $category == $item->id ) ? 'selected' : '' }}>{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="block-options">
                        <button id="filterBtn" type="submit" class="btn btn-primary"> {{ __('Filtrar') }} </button>

                    </div>

                </div>
            </form>
    </div>
</div>

@endsection

@section('block-header')

@endsection

@section('block-content')
<!-- DataTables init on table by adding .js-dataTable-buttons class, functionality is initialized at the top of this page -->
<div class="table-responsive">
    <table class="table table-bordered table-striped table-vcenter js-dataTable-full dataTable no-footer table-sm">
        <thead class="thead-light">
            <tr>
                <th ></th>
                <th class="text-center">{{ __('ID') }}</th>
                <th class="text-center">{{ __('Estado') }}</th>
                <th class="text-center">{{ __('Titulo') }}</th>
                <th class="text-center">{{ __('Author') }}</th>
                <th class="text-center">{{ __('Portada') }}</th>
                <th class="text-center">{{ __('Categorías') }}</th>

            </tr>
        </thead>
        <tbody>
            @forelse ($books as $item)
            <tr>

                <td class="text-center">
                    <a class="btn btn-sm btn-primary" href="{{route('books.edit',$item->id)}}" title="{{"Editar id $item->id"}}">
                        <i class="nav-main-link-icon si si-note"></i>
                    </a>
                </td>

                <td class="text-center">{{$item->id}}</td>
                <td class="text-center">{{$item->status == 1 ? 'Activo' : 'Inactivo' }}</td>
                <td class="text-center">{{$item->tittle }}</td>
                <td class="text-center">{{$item->author }}</td>
                <td class="text-center">
                    @php
                    $partes = explode(".", $item->tittle_page);
                    $extension = end($partes);
                    @endphp

                    @if($extension == 'jpg' || $extension == 'png' || $extension == 'gif' || $extension == 'jpeg')

                    <div class="animated fadeIn">
                        <a target="_blank" class="img-link img-link-zoom-in img-thumb img-lightbox magnific-pic" href="{{ (is_null($item->tittle_page)) ? '/media/avatars/avatar0.jpg' : Storage::disk('book_tittle_page')->url($item->tittle_page) }}">
                            <img class="img-fluid" style="width: 2.5rem;" src="{{ (is_null($item->tittle_page)) ? '/media/avatars/avatar0.jpg' : Storage::disk('book_tittle_page')->url($item->tittle_page) }}" alt="">
                        </a>
                    </div>
                    @else
                    <a class="btn btn-sm" href="{{ Storage::disk('book_tittle_page')->url($item->tittle_page) }}" target="_blank">
                        <i class="fas fa-file-alt" style="font-size: 1.5em"></i>
                    </a>
                    @endif
                </td>
                <td class="text-center">{{$item->categories->pluck('name')->implode(', ') }}</td>

            </tr>
            @empty
            <tr>
                <th scope="row" colspan="7" class="text-center">{{ __('Sin registros') }}</th>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>
@endsection

@push('js_after')


<script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-bs5/js/dataTables.bootstrap5.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/buttons.print.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/buttons.html5.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/buttons.flash.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('js/plugins/magnific-popup/jquery.magnific-popup.js') }}"></script>

<script src="{{ mix('js/pages/tables_datatables.js') }}"></script>
@endpush