routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController as Home;
use App\Http\Controllers\Catalog\CategoryController as Category;
use App\Http\Controllers\Catalog\BookController as Book;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return redirect('home');});
Route::get('/home', [Home::class, 'index'])->name('home');
Route::resource('/categories', Category::class);
Route::resource('/books', Book::class);

// Auth::routes();

app/Models/Catalog/Category.php
<?php

namespace App\Models\Catalog;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'status',
        'name'
    ];

    // Scopes
    public function scopeStatus($query, $status,$table = "")
    {
        if (!is_null($status) && $status !== "%" && $status !== "")
        {
          return !empty($table) ? $query->where("{$table}.status", $status): $query->where('status', $status);

        }

    }
}

app/Http/Controllers/Catalog/CategoryController.php
<?php

namespace App\Http\Controllers\Catalog;

use App\Http\Controllers\Controller;


use App\Models\Catalog\Category;
use App\Repositories\Catalog\CategoryRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{

    public $category_repository;

    public function __construct()
    {
        $this->category_repository = new CategoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = $this->category_repository->index($request->status_catagories);

        return view('catalogues.category.index', [
            'categories' => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $obj = new Category();

        // $spaces = $this->space_repository->findSpaceApi($headquarter_id);
        return view('catalogues.category.create', [
            'obj' => $obj
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try {


            $category = $this->category_repository->store($request);
            if (!$category->success) {
                DB::rollBack();
                return back()->withInput()->with(
                    'error',
                    __('msg.html_error_save') . $category->code .
                        __('msg.error_message') . $category->message
                );
            }

            DB::commit();

            return redirect()->route('categories.index')->with('success', $category->message);
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->withInput()->with(
                'error',
                __('msg.html_error_save') . $th->getCode() .
                    __('msg.error_message') . $th->getMessage()
            );
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Catalogues\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $obj = $this->category_repository->find($id);
        return view('catalogues.category.edit', [
            'obj' => $obj
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Catalogues\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $obj = Category::find($id);
        DB::beginTransaction();
        try {
            $category = $this->category_repository->update($request, $obj);
            if (!$category->success) {
                DB::rollBack();
                return back()->withInput()->with(
                    'error',
                    __('msg.html_error_save') . $category->code .
                        __('msg.error_message') . $category->message
                );
            }
            DB::commit();
            return redirect()->route('categories.index')->with('success', $category->message);
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->withInput()->with(
                'error',
                __('msg.html_error_save') . $th->getCode() .
                    __('msg.error_message') . $th->getMessage()
            );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Catalogues\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/catalogues/category/create.blade.php
@extends('layouts.app')

@push('css_after')
    <link rel="stylesheet" href="{{ asset('/js/plugins/flatpickr/themes/material_green.css') }}">
@endpush

@section('page-title')
    {{ __('Registrar Categoría') }}
@endsection

@section('block-header')
@if(session()->has('error'))
<div class="alert alert-danger alert-dismissible" role="alert">
    <p class="mb-0">
        {{session('error')}}
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif
@endsection

@section('block-content')
<form id="crud_form" method="POST" action="{{ route('categories.store')}} " enctype="multipart/form-data">
    @include('catalogues.category.form')
</form>
@endsection

@push('js_after')
    <script src="{{ asset('/js/plugins/flatpickr/flatpickr.min.js') }}"></script>
    <script src="{{ asset('/js/plugins/flatpickr/l10n/es.js') }}"></script>
@endpush

resources/views/catalogues/category/edit.blade.php
@extends('layouts.app')

@push('css_after')
    <link rel="stylesheet" href="{{ asset('/js/plugins/flatpickr/themes/material_green.css') }}">
    <link rel="stylesheet" href="{{ asset('/js/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/js/plugins/select2/css/select2-bootstrap4.min.css') }}">
@endpush

@section('page-title')
    {{ __('Editar Categoría') }}
@endsection

@section('block-header')
@if(session()->has('error'))
<div class="alert alert-danger alert-dismissible" role="alert">
    <p class="mb-0">
        {{session('error')}}
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif
@endsection

@section('block-content')
<form id="crud_form" method="POST" action="{{ route('categories.update', $obj) }}" class="crud_form">
    @method('PATCH')
    @include('catalogues.category.form' )
</form>
@endsection

@push('js_after')
    <script src="{{ asset('/js/plugins/flatpickr/flatpickr.min.js') }}"></script>
    <script src="{{ asset('/js/plugins/flatpickr/l10n/es.js') }}"></script>
    <script src="{{ asset('/js/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('/js/plugins/select2/js/i18n/es.js') }}"></script>
@endpush

resources/views/catalogues/category/form.blade.php
@csrf
<div class="form-group row mb-4">
    @if (!is_null($obj->id))
    <div class="form-group col-lg-3 col-md-4 col-sm-12">
        <label for="status">{{ __('Estado') }} <span class="text-danger">*</span></label><br>
        <select id="status" name="status" class="form-select @error('status') is-invalid @enderror" required>
            <option value="" {{ (old( "status",$obj->status) === null ) ? 'selected' :'' }}>{{ __('Seleccione') }}</option>
            <option value="1" {{ (old( "status",$obj->status) == "1" )  ? 'selected' :'' }}> {{ __('Activo') }}</option>
            <option value="0" {{ (old( "status",$obj->status) == "0" )  ? 'selected' :'' }}> {{ __('Inactivo') }}</option>
        </select>
        <span class="invalid-feedback" role="alert">
            <strong>@error('status'){{ $message }}@enderror</strong>
        </span>
    </div>
    @endif

    <div class="form-group col-lg-3 col-md-4 col-sm-12">
        <label for="name">{{ __('Nombre') }} <span class="text-danger">*</span></label><br>
        <input id="name" name="name" type="text" class="maxlength form-control @error('name') form-control-alt is-invalid @enderror"
         placeholder="{{ __('Nombre') }}" value="{{ old('name', $obj->name) }}" maxlength="50" required>
        <span class="invalid-feedback" role="alert">
            <strong>@error('name') {{ $message }} @enderror</strong>
        </span>
    </div>

</div>
<div class="form-group row mb-4">
    <div class="col-md-12">
        <button id="send" type="submit" class="btn btn-primary btn-md float-right">
            <i class="{{ (is_null($obj->id))  ? 'fas fa-save' : 'fas fa-sync-alt' }} mr-1"></i>
            {{ (is_null($obj->id)) ? __('Guardar') : __('Actualizar') }}
        </button>
        <a href="{{ route('categories.index') }}" class="btn btn-light btn-undo btn-md mr-2 float-right">
            <i class="fas fa-undo-alt mr-1"></i>{{ __('Regresar') }}
        </a>
    </div>
</div>

resources/views/catalogues/category/index.blade.php
@extends('layouts.app')

@push('css_before')
<link rel="stylesheet" href="{{ asset('js/plugins/datatables-bs5/css/dataTables.bootstrap5.css') }}">
<link rel="stylesheet" href="{{ asset('js/plugins/datatables/buttons-bs5/buttons.bootstrap5.min.css') }}">
<link rel="stylesheet" href="{{ asset('/js/plugins/magnific-popup/magnific-popup.css') }}">
@endpush

@section('page-title')
{{ __('Lista de categorías') }}
@endsection

@section('buttons')
{{-- {{ $util->generaBotones('parametros_generales', 'holidays.create', null) }} --}}
<a type="button" href="{{route('categories.create')}}" class="btn btn-success">Registrar Categoría</a>
@endsection

@section('block-extra')
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible" role="alert">
    <p class="mb-0">
        {{session('success')}}
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif


<form method="GET" action="" role="search" class="form-search">
    <div class="block block-rounded">
        <div class="block-content block-content-full">
            <div class="js-summernote-air">
                @csrf
                @php
                $status = request('status_catagories');
                @endphp
                <div class="block-header block-header-default text-center">
                    <div class="form-group  form-group-status col-md-3 col-sm-12" id="form-group-status">
                        <label for="status">{{ __('Estado') }}</label>
                        <select name="status_catagories" class="form-select" id="filter-index-status_catagories">
                            <option value='%' {{ ( $status == '%' ) ? 'selected' : '' }}>{{ __('Todos') }}</option>
                            <option value='1' {{ ( $status == '1' ) ? 'selected' : '' }}>{{ __('Activos') }}</option>
                            <option value='0' {{ ( $status == '0' ) ? 'selected' : '' }}>{{ __('Inactivos') }}</option>
                        </select>
                    </div>

                    <div class="block-options">
                        <button id="filterBtn" type="submit" class="btn btn-primary"> {{ __('Filtrar') }} </button>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

@section('block-header')
@endsection

@section('block-content')
<!-- DataTables init on table by adding .js-dataTable-buttons class, functionality is initialized at the top of this page -->
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover table-vcenter js-dataTable-full table-sm">
        <thead class="thead-light">
            <tr>
                <th></th>
                <th class="text-center">{{ __('ID') }}</th>
                <th class="text-center">{{ __('Estado') }}</th>
                <th class="text-center">{{ __('Nombre') }}</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($categories as $item)
            <tr>
        
                <td class="text-center">
                    <a class="extra_data btn btn-sm btn-primary" href="{{route('categories.edit',$item->id)}}" title="{{"Editar id $item->id"}}">
                        <i class="nav-main-link-icon si si-note"></i>
                    </a>
                </td>

                <td class="text-center">{{$item->id}}</td>
                <td class="text-center">{{$item->status == 1 ? 'Activo' : 'Inactivo' }}</td>
                <td class="text-center">{{$item->name }}</td>

            </tr>
            @empty
            <tr>
                <th scope="row" colspan="15" class="text-center">{{ trans('msg.noRecordsFound') }}</th>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>
@endsection

@push('js_after')

<script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-bs5/js/dataTables.bootstrap5.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/buttons.print.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/buttons.html5.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/buttons.flash.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables-buttons/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('js/plugins/magnific-popup/jquery.magnific-popup.js') }}"></script>

<script src="{{ mix('js/pages/tables_datatables.js') }}"></script>
@endpush